### PR TITLE
Add the new PHP 8.0 IntlDateFormatter::RELATIVE_* constants for date formatting

### PR DESCRIPTION
**Pull request by sukei**
Since PHP 8.0, IntlDateFormatter get new constants to format relative dates. This PR add those constants.

### CODE REVIEW

**Comment by rasstislav** [comment]
@fabpot Hello, what about that? I would need to use that too.

**Comment by sukei** [comment]
Just waiting for a review.

**Comment by fabpot** [comment]
Sorry, I missed it. This is a read-only split. Can you move your contrib on twigphp/twig instead?
Closing in the meantime as we cannot merge it here.

**Comment by sukei** [comment]
https://github.com/twigphp/Twig/pull/3808

**Pull request closed without merging**
